{
  config: {
    url: 'login',
    method: 'post',
    data: '{"email":"01@test.io","password":"1234"}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=utf-8'
    },
    baseURL: 'http://localhost:8000/api/',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    withCredentials: true,
    adapter: [Function: xhrAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: XMLHttpRequestOverride {
    _events: [],
    UNSENT: 0,
    OPENED: 1,
    HEADERS_RECEIVED: 2,
    LOADING: 3,
    DONE: 4,
    onreadystatechange: [Function: handleLoad],
    onabort: [Function: handleAbort],
    onerror: [Function: handleError],
    onload: null,
    onloadend: null,
    onloadstart: null,
    onprogress: null,
    ontimeout: [Function: handleTimeout],
    url: 'http://localhost:8000/api/login',
    method: 'POST',
    readyState: 4,
    withCredentials: true,
    status: 400,
    statusText: 'Bad Request',
    data: '{"email":"01@test.io","password":"1234"}',
    response: '',
    responseType: 'text',
    responseText: '',
    responseXML: null,
    responseURL: '',
    upload: null,
    timeout: 0,
    _requestHeaders: HeadersPolyfill { _headers: [Object], _names: [Map] },
    _responseHeaders: HeadersPolyfill { _headers: [Object], _names: [Map] },
    async: true,
    user: undefined,
    password: undefined
  },
  response: {
    data: '',
    status: 400,
    statusText: 'Bad Request',
    headers: { 'x-powered-by': 'msw' },
    config: {
      url: 'login',
      method: 'post',
      data: '{"email":"01@test.io","password":"1234"}',
      headers: [Object],
      baseURL: 'http://localhost:8000/api/',
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      withCredentials: true,
      adapter: [Function: xhrAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: XMLHttpRequestOverride {
      _events: [],
      UNSENT: 0,
      OPENED: 1,
      HEADERS_RECEIVED: 2,
      LOADING: 3,
      DONE: 4,
      onreadystatechange: [Function: handleLoad],
      onabort: [Function: handleAbort],
      onerror: [Function: handleError],
      onload: null,
      onloadend: null,
      onloadstart: null,
      onprogress: null,
      ontimeout: [Function: handleTimeout],
      url: 'http://localhost:8000/api/login',
      method: 'POST',
      readyState: 4,
      withCredentials: true,
      status: 400,
      statusText: 'Bad Request',
      data: '{"email":"01@test.io","password":"1234"}',
      response: '',
      responseType: 'text',
      responseText: '',
      responseXML: null,
      responseURL: '',
      upload: null,
      timeout: 0,
      _requestHeaders: [HeadersPolyfill],
      _responseHeaders: [HeadersPolyfill],
      async: true,
      user: undefined,
      password: undefined
    }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}